---
title: "class-03-05"
author: "Carina Peng"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(ggplot2)
library(janitor)
library(tidyverse)

sheets_deauth()
```

```{r}

# There is nothing wrong with reading in, and cleaning up, your data in the
# setup R code chunk. But, to be honest, I am just doing this here because I
# couldn't figure out how to turn off the message from read_sheet.

x <- read_sheet(ss =  "14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA") %>% 
  clean_names() %>%
  mutate(percent_red = red / 25)

summary(x)
```

```{r}
x %>% 
  ggplot(aes(percent_red)) +
    geom_histogram(bins = 20) +
    labs(title = "Percentage of Red Beads Drawn",
        subtitle = "Should we be suspicious of those outliers?",
        caption = "Classroom data from 2020-03-03",
        x = "Percentage of Red Beads Out of 25 Drawn",
        y = "Count") 
```

```{r}

# Create a virtual represnetation of a physical process

urn <- tibble(bean_ID = 1:10000,
              color = c(rep("Red", 2000), rep("White", 8000)))

# Use sample_n to sample 10 times

urn %>% sample_n(10)

```


